### ISSUE TITLE
How can we get patch result through call doGet for the current resource?

### ISSUE THREAD

**Issue by lzy1212003** [openbmc/bmcweb#129]
Because of the asynchronous operation of ASIO, the patch operation will return quickly and not get patch body result. How can we call doGet after patch operation to return the result of the current operation?

**Comment by feistjj** [comment]
Patch calls only return status. You can do an http GET to all the doGet method

**Comment by lzy1212003** [comment]
“For update, replace, and delete operations, the response from the service, after successful modification,should be one of the following responses:
• The HTTP 200 OK status code with a body that contains the JSON representation of the targeted resource after the modification has been applied, or, for the delete operation, a representation of the deleted resource.”,this is the explication for patch result from DSP0266 . 
Therefore, I think patch operation should return the get result of the resource. am I right？
So how to get the result information of the resource synchronously after modifying it？could the function of "yield_ method_ Call"  realize this function ?  thanks! @feistjj

**Comment by edtanous** [comment]
You carefully cut off the part of the specification that's relevant here.  The text you quoted continues with another option
```
The HTTP 204 No Content status code with empty payload in the event that the service
cannot return a representation of the created resource.
```
This is the option bmcweb implements for most of its PATCH interfaces.  bmcweb is well within the specification to do so.

Note, what you are asking for is not available by design, as in practice, it tends to require 2x the number of dbus calls for something that can be done already.  At one point, bmcweb implemented PATCH operations as you wished, by returning the new resource in question.  That was removed in lieu of the 204 response, which is correct, and much more performant.

**Comment by lzy1212003** [comment]
thanks！
but, many patch operations return results with a status code of 200, and the response body is message extension information. Is this not compliant with redfish specifications！

**Comment by edtanous** [comment]
Per the line in the spec, on the line that I quoted, there is nothing in the specification that requires PATCH operations to return a 200, with the response body.  This is implementation dependent, and the bmcweb implementation chooses to return 204 (for good reason).
If you can quote the portion of the specification that states that a Redfish implementation MUST return 200, it's possible I'm mistaken, but the portion we've each quoted seems to make it clear that it's up to the implementer.

**Comment by lzy1212003** [comment]
ok
