### ISSUE TITLE
boost-url moved permanently ? 

### ISSUE THREAD

**Issue by frsauvage** [openbmc/bmcweb#177]
Hi ,

`git clone bmcweb`
run 
`build_x86_docker.sh` 
(I changed to podman : build_x86_podman.sh nearly identical)

I get :
![image](https://user-images.githubusercontent.com/23147820/105329425-6d00e600-5bd1-11eb-8cb7-30e4fa8f63e9.png)

I curl it:

![image](https://user-images.githubusercontent.com/23147820/105329914-f9aba400-5bd1-11eb-84a0-566224a1f796.png)

Did I miss something ?

Best Regards,

**Comment by manojkiraneda** [comment]
Hi @frsauvage ,
I am not sure i understand the problem correctly , but 
**Subproject boost-url is buildale : No**
is expected to come, meson expects all the subprojects to  have meson build system, and boost-url is based on cmake, which is why it says its not buildable which is okay.

bmcweb uses the boost-url code as a header only library, so there is no need for us to build the package to consume it inside the bmcweb. Are you facing any compilation failure ?

the source code of boost-url is at : https://github.com/CPPAlliance/url
I think you need to git clone rather than curl

**Comment by frsauvage** [comment]
Thank you @manojkiraneda , my mistake, I copy/paste and I miss the '.git extension.'
I did not know about not buildable behavior.
Regards,
Francine
