### ISSUE TITLE
Redfish: Processor Internal error

### ISSUE THREAD

**Issue by gtmills** [openbmc/bmcweb#18]
On a witherspoon with a recent master builld
```
bash-4.1$ curl -k -H "X-Auth-Token: $bmc_token" -X GET https://${bmc}/redfish/v1/Systems/motherboard/Processors/cpu0
{
  "@odata.context": "/redfish/v1/$metadata#Processor.Processor",
  "@odata.id": "/redfish/v1/Systems/motherboard/Processors/cpu0",
  "@odata.type": "#Processor.v1_1_0.Processor",
  "Id": "cpu0",
  "Name": "Processor",
  "error": {
    "@Message.ExtendedInfo": [
      {
        "@odata.type": "/redfish/v1/$metadata#Message.v1_0_0.Message",
        "Message": "The request failed due to an internal service error.  The service is still operational.",
        "MessageArgs": [],
        "MessageId": "Base.1.4.0.InternalError",
        "Resolution": "Resubmit the request.  If the problem persists, consider resetting the service.",
        "Severity": "Critical"
      }
    ],
    "code": "Base.1.4.0.InternalError",
    "message": "The request failed due to an internal service error.  The service is still operational."
  }
}
```
This is caused by the ProcessorCoreCount property not existing. 
https://github.com/openbmc/bmcweb/blob/8c20c72f4eeeda4b17e5a3f113965a5aa94944ce/redfish-core/lib/cpudimm.hpp#L89
Where does this ProcessorCoreCount come from? What interface? 

```
curl -b cjar -k  https://${BMC_IP}/xyz/openbmc_project/inventory/system/chassis/motherboard/cpu0
{
  "data": {
    "BuildDate": "1996-01-01 - 00:00:00", 
    "Cached": false, 
    "FieldReplaceable": true, 
    "Functional": true, 
    "Manufacturer": "IBM", 
    "Model": "", 
    "PartNumber": "02AA969", 
    "Present": true, 
    "PrettyName": "PROCESSOR MODULE", 
    "SerialNumber": "YA1934232158", 
    "Version": "21"
  }, 
  "message": "200 OK", 
  "status": "ok"
}
```

**Comment by edtanous** [comment]
For Intel systems, this is coming from the xyz.openbmc_project.Item.Cpu interface
https://github.com/openbmc/phosphor-dbus-interfaces/blob/master/xyz/openbmc_project/Inventory/Item/Cpu.interface.yaml

I suspect the bug here is that we need to do something more sane if that count doesn't exist, like not including that property.

The line that's killing you is right here:
https://github.com/openbmc/bmcweb/blob/63c7908ddb4647c995f1cb0e121e6b313146ada9/redfish-core/lib/cpudimm.hpp#L92
It looks like the current implementation is using it to switch whether or not the processor is present.

I put together an (untested) patch that may fix your issues here (although probably doesn't get you 100% of the way to a working resource)

https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/16544
