### ISSUE TITLE
Unknown method endpoints or interface xyz.openbmc_project.Association.

### ISSUE THREAD

**Issue by esm** [openbmc/bmcweb#219]
**Describe the bug**
 what():  sd_bus_call: org.freedesktop.DBus.Error.UnknownMethod: Unknown method endpoints or interface xyz.openbmc_project.Association.
I have created a dbus object and requested the name xyz.openbmc_project.Association for my service file. I can see the xyz.openbmc_project.Association service running when I run busctl but fails in sensors.hpp:1348 when trying to the endpoint method on the Association interface. Is there a service file for xyz.openbmc_project.Association? I could not find it in this repo. If not, how do I make Association work?

**Environment**
What OpenBMC platform was this found on? romulus
What specific OpenBMC versions did you use? master

**To Reproduce**
1. Run the command '....' ./bmcweb,  run webui-vue (front-end),  and monitor the system bus
2. See error what():  sd_bus_call: org.freedesktop.DBus.Error.UnknownMethod: Unknown method endpoints or interface xyz.openbmc_project.Association.
3. Expected behavior was '....' no failure

**Is this a regression**
Has this behavior worked in the past? no

**Comment by edtanous** [comment]
"master" is not a version, and changes every day.  Please list a specific sha, as the template requests.

When you say "romulus" were you actually on a romulus platform?

That's a surprising error to see at bmcweb startup, considering bmcweb does no dbus transactions at startup.  Are you certain you didn't miss any steps?

Your bug seems to look a lot like a question about how associations work, rather than reporting a bug.  I suspect the mailing list or discord would be a better place to try to get support.
