### ISSUE TITLE
$metadata has incorrect Reference tag

### ISSUE THREAD

**Issue by maximyep** [openbmc/bmcweb#57]
Get /redfish/v1/$metadata
go to the end of the file:
  <edmx:Reference Uri="/redfish/v1/schema/OemManager_v1.xml" /> **<--- "/" is not needed!**
  <edmx:Include Namespace="OemManager" />
  </edmx:Reference>

Full file: 
[openbmc.metadata.txt](https://github.com/openbmc/bmcweb/files/2914723/openbmc.metadata.txt)

The sceenshot:
![2019-02-28 13_21_43-d__openbmc metadata xml - notepad](https://user-images.githubusercontent.com/3142364/53563146-d568f900-3b5b-11e9-80bc-638cd58a6c35.png)

Test was done using QEMU: 2.6.0-rc1-303-g4430f2d

**Comment by edtanous** [comment]
The bug description doesn't give any backup on _why_ this needs to be removed.  bmcweb produces an OemManager object in the Managers repo, so it's not clear why this would be removed.

Failing validator checks can be fixed by either disabling checking of Oem schemas in your config, or downloading the above referenced file, and insert it into your root store.

**Comment by edtanous** [comment]
Per IRC, @devenrao is looking into this

**Comment by devenrao** [comment]
Pushed changes
https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/18792/

**Comment by edtanous** [comment]
Code merged.  Closing
