### ISSUE TITLE
DMTF: Redfish Conformance-Check is not passed well: 14 errors were thrown

### ISSUE THREAD

**Issue by maximyep** [openbmc/bmcweb#65]
- [x] <--- Assertion 6.1.9: FAIL
- [ ] <--- Assertion 6.1.14: FAIL
- [ ] <--- Assertion 6.4.2.2: FAIL
- [ ] <--- Assertion 6.4.2.3: FAIL
- [ ] <--- Assertion 6.4.13: FAIL
- [x] <--- Assertion 6.4.18: FAIL
- [ ] <--- Assertion 6.4.26: FAIL
- [ ] <--- Assertion 6.5.1: FAIL
- [ ] <--- Assertion 6.5.3: FAIL
- [ ] <--- Assertion 6.5.6.9: FAIL
- [ ] <--- Assertion 6.5.6.10: FAIL
- [ ] <--- Assertion 7.5.3: FAIL
- [ ] <--- Assertion 7.5.5: FAIL
- [ ] <--- Assertion 7.5.8: FAIL
- [ ] <--- Assertion 7.5.9: FAIL
- [x] <--- Assertion 7.5.14: FAIL
- [x] <--- Assertion 7.5.14.1: FAIL
- [ ] <--- Assertion 7.5.16: FAIL

Steps to reproduce:
Download https://github.com/DMTF/Redfish-Service-Conformance-Check
Update the properties.json with:
```
  "RedfishServiceCheckTool_SUTConfiguration": {
    "SUTs": [
        {
        "Password": "0penBmc",
        "LoginName": "root",
        "AllowAction_LogServiceClearLog": "yes",
        "DnsName": "192.168.122.52:443",
        "DisplayName": "Bmc",
        "RedfishVersion": "v1",
        "NumUrisToCache": "25",
	"UseHttp": "no"
      }
```

Start a test: python3 sample_run.py

Pay attention to "FAIL" in the logs:
[sample_run.txt](https://github.com/openbmc/bmcweb/files/2977596/sample_run.txt)

**Comment by edtanous** [comment]
I don't know of anyone that has run this tools on bmcweb before.  With that said, I look forward to seeing patches that bring us into better compliance.
I took a quick skim through this.  A majority of the issues can be boiled down to 3 categories:
1. Ignoring verbs/ bad response codes on certain verbs (GET/POST/PATCH/TRACE).  There are a number of cases where we should be returning errors but aren't.  This could be fixed in a pretty easy patchset.
2. expected 406, method not acceptable codes.  This is on things like GET /redfish/v1/Chassis.  It's not clear why that would trigger a 406 error.  Someone will need to look into that.
3. ETag headers.  bmcweb doesn't yet support ETag headers, and to my understanding of the specification they are optional  This is likely just a matter of bmcweb publishing support for something that we don't actually support.  Someone will need to triage further.
4. Checking oData version flags.  At this point, the odata version flags are completely ignored.  This would need to be resolved.
5. Query parameters ignored unless supported.  It looks like Redfish expects error codes if the parameters are provided, but the implementation doesn't support them.
More......

Most of these can be boiled down to a disagreement about error handling procedures.  This could certainly be improved in bmcweb, but I don't see any that would cause a significant impact to the golden path.  With that said, any and all patches are appreciated to resolve some or all of these.

**Comment by edtanous** [comment]
Can you please retest with this patch, and report back?

https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/19652

**Comment by maximyep** [comment]
4 Assertions are PASSED now. Current log:

[rf-assertions-log.bb.txt](https://github.com/openbmc/bmcweb/files/3017030/rf-assertions-log.bb.txt)

**Comment by edtanous** [comment]
This tool has been deprecated by DMTF, and the replacement, Redfish-Protocol-Validator, is something that bmcweb is now fully passing. 

Closing.
