### ISSUE TITLE
Converge or configure HTTP response headers

### ISSUE THREAD

**Issue by joseph-reynolds** [openbmc/bmcweb#9]
As we move off of nginx and onto bmcweb, I want to ensure that bmcweb writes the correct HTTP response headers.  Currently there are several nginx config files, e.g.,
 - https://github.com/openbmc/meta-ibm/blob/master/recipes-httpd/nginx/files/nginx.conf
 - https://github.com/openbmc/openbmc/blob/4feb727cd6b77a68bdaca63e121b378d814f5eaf/meta-openembedded/meta-webserver/recipes-httpd/nginx/files/nginx.conf
 - more?

Further, note meta-ibm nginx.conf adds HTTP response headers based on the URI being processed, e.g.:
 - for HTTP, the Strict-Transport-Security header should not be used
 - for the web app (URI=/), additional headers are needed that are not needed for REST APIs
 - Etc.

I would like to be able to converge all these into a single set of defaults (so no configuration is needed).  But I don't have a strong background in this area.

**Comment by edtanous** [comment]
bmcweb currently targets the OWASP http security headers here:
https://www.owasp.org/index.php/OWASP_Secure_Headers_Project#tab=Best_Practices

This is documented in the Developing.md file inside the repo.

The only exception to that list is our lack of Public Key Pinning, given how BMCs are generally provisioned, keys can be changed, so key pinning is not desired or required.

"for HTTP, the Strict-Transport-Security header should not be used"
Why?  While HSTS headers are ignored on HTTP connections, no harm is caused by including them.

"for the web app (URI=/), additional headers are needed that are not needed for REST APIs"
Do you have examples of headers that bmcweb should be setting that it isn't today?  Today bmcweb sets the same security headers regardless of mime-type.  Feel free to submit a pull request if you think this should be changed to headers per-mime, but currently the extra headers don't hurt anything, so this is a very low priority.

"I would like to be able to converge all these into a single set of defaults (so no configuration is needed). But I don't have a strong background in this area."
I believe bmcweb has already done this, and security headers are generated from this file:
https://github.com/openbmc/bmcweb/blob/master/include/security_headers_middleware.hpp

**Comment by edtanous** [comment]
Can this issue be closed?

**Comment by joseph-reynolds** [comment]
13 days? ... I have been distracted.  I am looking at differences between https://gerrit.openbmc-project.xyz/#/c/openbmc/meta-ibm/+/14800/1/recipes-httpd/nginx/files/nginx.conf and https://github.com/openbmc/bmcweb/blob/master/include/security_headers_middleware.hpp. The significant differences are:
 - X-Content-Security-Policy -vs- Content-Security-Policy
 - Content-Security-Policy value changed to: "script-src 'self'; object-src 'self'"  (we need the "unsafe" values for AngularJS function, but that's another issue)

The presence of the Strict-Transport-Security header on HTTP(notS) responses triggered a warning from a security scanner that pointed out the header was ineffective.  I suppose we could ignore that warning.

**Comment by edtanous** [comment]
It looks like you've found exactly where the changes need to be made.  Do you think you could open a gerrit review for the changes you're proposing, and we'll go from there.

**Comment by joseph-reynolds** [comment]
Created review for this: https://gerrit.openbmc-project.xyz/#/c/openbmc/bmcweb/+/15765.
Closing this issue.
