### ISSUE TITLE
XAuthToken: Reset of auth-token.

### ISSUE THREAD

**Issue by ratagupt** [openbmc/bmcweb#95]
@edtanous 
This issue is just to get your feedback.I was not sure that the following use-case is a security issue or not.

Currently in bmcweb we create the session and that creates the X-Auth Token and this token works fine even if the bmcweb crashes and restart again.

If bmcweb crashes should we keep the auth-tokens or reset it?

I also tried to reboot the bmc even the token which I took before the reboot was valid after the bmc reboot.

Is it some security concern?

**Comment by edtanous** [comment]
I don’t believe it is, but I’d like to hear your thinking on it.  The intent was to allow user sessions survive a reboot so that firmware update or cold reset wouldn’t require a relogin, as it does on a lot of BMCs.
Session timeouts, and credentials are still enforced after a reboot, so the thinking was that it has roughly the same security model as if the BMC had never rebooted, with the exception of the persistent data being vulnerable.
Can you give some more details on why you think it’s a security issue?

**Comment by ratagupt** [comment]
Ed, Thanks for the reply, Just wanted to bring this.

# ls -la /home/root/bmcweb_persistent_data.json
-rw-r--r--    1 root     root           509 Jul  9 13:13 /home/root/bmcweb_persistent_data.json
This json is having all the session info, now suppose some user gets logged in via non root privilege and read this file, get the session which is having admin privilege, then he can send the HTTP query with the X-auth token having admin privilege.

**Comment by edtanous** [comment]
That's an excellent point, we could certainly improve the permissions on this file to disallow group read access.  I'd be happy to look at the code review.

**Comment by ratagupt** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/23480
